[theme]
primaryColor = "#2c2e3a"
backgroundColor = "#f8f4fc"
secondaryBackgroundColor = "#141619"
textColor = "#fffff"
#font = "sans serif"

#[theme]
#primaryColor = "#f4b41a"
#backgroundColor = "#f4b41a"
#secondaryBackgroundColor = "#143d59"
#textColor = "FFFFFF"
#font = "sans serif"
