[theme]
primaryColor = "#9d9ad9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#cedef0"
#font = "sans serif"

#[theme]
#primaryColor = "#f4b41a"
#backgroundColor = "#f4b41a"
#secondaryBackgroundColor = "#143d59"
#textColor = "FFFFFF"
#font = "sans serif"
